version: '3.8'
services:
    postgres-fisio:
        image: postgres:17.0
        env_file:
            - .env
        ports:
            - 5433:5432
        volumes:
            - dados_fisio:/var/lib/postgresql/data
    redis:
        image: redis:8-alpine

        ports:
            - 6379:6379
volumes:
    dados_fisio: