"""criação das colunas de horas dos agendamentos

Revision ID: 07231d6faa2a
Revises: e9a819aca90f
Create Date: 2026-04-01 15:20:49.835637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07231d6faa2a'
down_revision: Union[str, Sequence[str], None] = 'e9a819aca90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('data_hora_inicio', sa.DateTime(), nullable=False))
    op.add_column('agendamentos', sa.Column('data_hora_fim', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'data_hora_fim')
    op.drop_column('agendamentos', 'data_hora_inicio')
    # ### end Alembic commands ###
