"""rename type_service to category

Revision ID: 7dd65269414c
Revises: ba3ccf407f8d
Create Date: 2026-04-26 18:54:00.770734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd65269414c'
down_revision: Union[str, Sequence[str], None] = 'ba3ccf407f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Cria o novo tipo Enum no PostgreSQL
    sa.Enum('ODONTOLOGICO', 'ESTETICO', name='servicecategory').create(op.get_bind())
    
    op.add_column('servicos', sa.Column('category', sa.Enum('ODONTOLOGICO', 'ESTETICO', name='servicecategory'), nullable=False))
    op.drop_column('servicos', 'type_service')
    
    # Remove o tipo Enum antigo
    sa.Enum('ODONTOLOGICO', 'ESTETICO', name='servicetype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ODONTOLOGICO', 'ESTETICO', name='servicetype').create(op.get_bind())
    
    op.add_column('servicos', sa.Column('type_service', postgresql.ENUM('ODONTOLOGICO', 'ESTETICO', name='servicetype'), autoincrement=False, nullable=False))
    op.drop_column('servicos', 'category')
    
    sa.Enum('ODONTOLOGICO', 'ESTETICO', name='servicecategory').drop(op.get_bind())
    # ### end Alembic commands ###
