"""adicionando colunas de recuperacao de senha

Revision ID: 7fb0667454b6
Revises: 7dd65269414c
Create Date: 2026-04-26 19:07:50.478526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb0667454b6'
down_revision: Union[str, Sequence[str], None] = '7dd65269414c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_password_code', sa.String(length=6), nullable=True))
    op.add_column('usuarios', sa.Column('reset_password_expire', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'reset_password_expire')
    op.drop_column('usuarios', 'reset_password_code')
    # ### end Alembic commands ###
