"""adicionando tabela para imagem e tipo do servico

Revision ID: ba3ccf407f8d
Revises: 07d2231d2e37
Create Date: 2026-04-26 18:21:02.041667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3ccf407f8d'
down_revision: Union[str, Sequence[str], None] = '07d2231d2e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar o tipo ENUM manualmente para o PostgreSQL
    service_type_enum = sa.Enum('ODONTOLOGICO', 'ESTETICO', name='servicetype')
    service_type_enum.create(op.get_bind())

    op.add_column('servicos', sa.Column('type_service', service_type_enum, nullable=False))
    op.add_column('usuarios', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'profile_picture')
    op.drop_column('servicos', 'type_service')

    # Remover o tipo ENUM manualmente
    sa.Enum(name='servicetype').drop(op.get_bind())
    # ### end Alembic commands ###
