"""Adicionar status_conta ao provider para soft delete

Revision ID: e9a819aca90f
Revises: c46ca79f5814
Create Date: 2026-03-27 15:11:57.604129

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a819aca90f'
down_revision: Union[str, Sequence[str], None] = 'c46ca79f5814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Primeiro: Criamos o tipo Enum explicitamente no banco
    status_enum = postgresql.ENUM('ATIVO', 'INATIVO', name='statusprovider')
    status_enum.create(op.get_bind())

    # 2. Segundo: Adicionamos a coluna usando o tipo que acabamos de criar
    op.add_column('providers', sa.Column(
        'operando', 
        sa.Enum('ATIVO', 'INATIVO', name='statusprovider'), 
        server_default='ATIVO', 
        nullable=False
    ))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'operando')
    # ### end Alembic commands ###
